#!/usr/bin/env bash

set -eux

cd "${0%/*}/.."

npm install

pushd client
npm install
popd

pushd terminal-client
npm install
popd

git submodule init
git submodule update

pushd game/prometheus-cpp

git submodule init
git submodule update

mkdir _build
cd _build

cmake .. -DBUILD_SHARED_LIBS=ON -DENABLE_PUSH=OFF -DENABLE_COMPRESSION=OFF
cmake --build . --parallel 4
sudo cmake --install .
sudo ldconfig
