#!/usr/bin/env bash

set -eux

cd "${0%/*}/.."

# Install nix
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux \
  --extra-conf "sandbox = false" \
  --init none \
  --no-confirm

# Install npm packages for main project
nix develop -c npm install

# Install and build crates for auth server
pushd auth
nix develop -c cargo build
popd

# Install npm packages for client, and terminal-client
pushd client
nix develop -c npm install
popd

pushd terminal-client
nix develop -c npm install
popd

# Initialize and update git submodules
git submodule init
git submodule update

# Build Prometheus C++ client library
pushd game/prometheus-cpp

git submodule init
git submodule update

# Check if _build directory exists, create it if not
mkdir -p _build

# Change to _build directory
cd _build

# Build Prometheus C++ client library
nix develop -c cmake .. -DBUILD_SHARED_LIBS=ON -DENABLE_PUSH=OFF -DENABLE_COMPRESSION=OFF
nix develop -c cmake --build . --parallel 4

# Install Prometheus C++ client library and update linker cache
nix develop -c cmake --install .
nix develop -c ldconfig
