name: Deploy Nginx

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Deploy
      uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
      with:
        host: rollycubes.com
        user: root
        key: ${{ secrets.DO_SSH_KEY }}
        first_ssh: |
          mkdir -p /root/nginx
          cd /root/nginx
          docker-compose down || true
          rm -rf config
          mkdir -p config
        scp: |
          nginx => '/root'
        last_ssh: |
          cd /root/nginx
          docker-compose up -d
